
apiVersion: apps/v1
kind: Deployment

metadata:
  name: anime-service
  namespace: anime-store

spec:
  replicas: 2

  selector:
    matchLabels:
      app: anime-service

  template:
    metadata:
      labels:
        app: anime-service

    spec:
      containers:
        - name: anime-service
          image: nuthan22/pyanimese:21

          ports:
            - containerPort: 8000

          env:
            - name: DATABASE_URL
              value: "postgresql://anime:animepass@postgres:5432/anime_store"
