apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
  namespace: anime-store
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS anime_items (
        id SERIAL PRIMARY KEY,
        name VARCHAR(100) NOT NULL,
        description TEXT,
        price DECIMAL(10,2) NOT NULL
    );

    INSERT INTO anime_items (name, description, price)
    VALUES
    ('Naruto', 'Naruto Uzumaki anime item', 500),
    ('One Piece', 'One Piece anime item', 600),
    ('Dragon Ball', 'Dragon Ball anime item', 700);
